### ISSUE TITLE
Recursion depth error introduced by non-conventional message id formats

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/ACE#111]
We got an email with this surprisingly valid message ID format:

`Message-Id: <202008071357206818278@example.com>+4099DCB271A60273`

Scrubbed engine logs:
```
[2020-08-07 01:58:01,788] [__init__.py:1999] [MainThread] [1642] [INFO] - processing ACE Mailbox Scanner Detection - c6b65fbc-ef2b-4f8f-9ba7-3bcb12fa95c7 mode email (e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4)
[2020-08-07 01:58:01,789] [__init__.py:2376] [MainThread] [1642] [INFO] - starting analysis on RootAnalysis(e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4) with a workload of 1
[2020-08-07 01:58:01,909] [email.py:1713] [MainThread] [1642] [INFO] - scanning email [e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4] <202008071357206818278@example.com>+4099DCB271A60273 from "windowsfunk@example.com" <windowsfunk@example.com> to ['unixfreak@example.com'] subject =?GB2312?B?xM/NqLuvx+GxvdLSz6lDT0E=?=
[2020-08-07 01:58:02,135] [__init__.py:2742] [MainThread] [1642] [ERROR] - analysis module URLExtractionAnalyzer failed on WorkTarget(obs:file(email.rfc822.unknown_text_html_000),analyis:None,module:None,dep:None) for RootAnalysis(e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4) reason maximum recursion depth exceeded
[2020-08-07 01:58:02,550] [__init__.py:2742] [MainThread] [1642] [ERROR] - analysis module URLExtractionAnalyzer failed on WorkTarget(obs:file(email.rfc822.unknown_text_html_000),analyis:None,module:None,dep:None) for RootAnalysis(e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4) reason maximum recursion depth exceeded
[2020-08-07 01:58:02,650] [__init__.py:2392] [MainThread] [1642] [INFO] - entering final analysis for RootAnalysis(e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4)
[2020-08-07 01:58:02,686] [__init__.py:2078] [MainThread] [1642] [INFO] - completed analysis RootAnalysis(e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4) in 0.90 seconds
```

Truncated error report:
```
CURRENT ENGINE: Engine (ace-qa.local - ace)
CURRENT ANALYSIS TARGET: RootAnalysis(e8b4990e-8e05-4f5e-8d8a-dc6db550b5a4)
CURRENT ANALYSIS MODE: email
EXCEPTION
maximum recursion depth exceeded

STACK TRACE
Traceback (most recent call last):
  File "/opt/ace/saq/engine/__init__.py", line 2653, in execute_module_analysis
    analysis_result = analysis_module.analyze(work_item.observable, final_analysis_mode)
  File "/opt/ace/saq/modules/__init__.py", line 846, in analyze
    analysis_result = self.execute_analysis(obj)
  File "/opt/ace/saq/modules/file_analysis.py", line 3423, in execute_analysis
    extracted_urls = find_urls(fp.read(), base_url=base_url)
  File "/usr/local/lib/python3.6/dist-packages/urlfinderlib/urlfinderlib.py", line 28, in find_urls
    urls |= finders.HtmlUrlFinder(blob, base_url=base_url).find_urls()
  File "/usr/local/lib/python3.6/dist-packages/urlfinderlib/finders/html.py", line 37, in find_urls
    urls |= HtmlSoupUrlFinder(soup, base_url=self._base_url).find_urls()
  File "/usr/local/lib/python3.6/dist-packages/urlfinderlib/finders/html.py", line 51, in find_urls
    possible_urls |= {urljoin(self._base_url, u) for u in self._get_base_url_eligible_values()}
  File "/usr/local/lib/python3.6/dist-packages/urlfinderlib/finders/html.py", line 94, in _get_base_url_eligible_values
    values |= self._get_css_url_values()
  File "/usr/local/lib/python3.6/dist-packages/urlfinderlib/finders/html.py", line 104, in _get_css_url_values
    re.findall(r"url\s*\(\s*[\'\"]?(.*?)[\'\"]?\s*\)", str(self._soup), flags=re.IGNORECASE)}
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1491, in __unicode__
    return self.decode()
  File "/usr/local/lib/python3.6/dist-packages/bs4/__init__.py", line 745, in decode
    indent_level, eventual_encoding, formatter)
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1599, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1693, in decode_contents
    formatter))
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1599, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1693, in decode_contents
    formatter))

  { removed hundreds of lines }

  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1599, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1693, in decode_contents
    formatter))
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1599, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1693, in decode_contents
    formatter))
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1599, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 1690, in decode_contents
    text = c.output_ready(formatter)
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 925, in output_ready
    output = self.format_string(self, formatter)
  File "/usr/local/lib/python3.6/dist-packages/bs4/element.py", line 209, in format_string
    output = formatter.substitute(s)
  File "/usr/local/lib/python3.6/dist-packages/bs4/formatter.py", line 86, in substitute
    from .element import NavigableString
RecursionError: maximum recursion depth exceeded
```

If I try to manually correlate the message_id ACE does not find anything. As a test, I removed the message_id normalization and then ace found the email history but still failed to locate the email in the archive.
 
¯\\_(ツ)_/¯

**Comment by unixfreak0037** [comment]
I think this may have been an issue in the urlfinderlib that Matt may have already fixes. Cannot reproduce locally.
